api.http.host: 0.0.0.0
api.http.port: 9600
node.name: logstash
path.config: /usr/share/logstash/config/logstash.conf
pipeline.batch.delay: 50
pipeline.batch.size: 125
pipeline.workers: 2
xpack.monitoring.elasticsearch.hosts:
- http://es01:9200
xpack.monitoring.enabled: false